name: Job Scraper

on:
  schedule:
    - cron: "0 * * * *"     # hourly on the hour
  workflow_dispatch:         # manual

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/tier1.csv data/tier2.csv data/run_history.csv data/first_seen.csv || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "auto: update job sweep"
            git push origin master
          fi
