name: Job Scraper

on:
  schedule:
    - cron: "0 * * * *"   # run every hour on the hour
  workflow_dispatch:       # allow manual run from GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas

      - name: Run scraper
        run: |
          python scraper.py

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add tier1.csv tier2.csv
          git diff --cached --quiet || git commit -m "auto: update job sweep"
          git push
